### ISSUE TITLE
Conflict between begin_cat and obbrowser pipe

### ISSUE THREAD

**Issue by willbelr** [trizen/obbrowser#2]
A name that is used in an obbrowser pipe cannot be used as a category name. 

    #{pipe => ['obbrowser ~/', 'Conflicting Name', '']},
    {begin_cat => ['Conflicting Name', '']},
        {item => ['', 'This entry is not shown', '']},
    {end_cat => undef},

For exemple, if the first line is uncommented, the category "Conflicting Name" will be replaced by the obbrowser pipe to ~/.

**Comment by trizen** [comment]
I think this needs to be fixed in obmenu-generator, by generating a unique ID for each category. Thanks for reporting this.

**Comment by trizen** [comment]
The issue has been fixed in obmenu-generator.
